---
title: "scATAC Sequencing Sample Summary: `r {params$in_sample}`"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    self_contained: true
  tables: yes
params:
  in_sample: NULL
  in_dir: NULL
  in_key: NULL
  in_method: NULL
  out_dir: NULL
  scATAC_report_version: 1.0.0
---  

# {.tabset}  

## Sample Summary {.active} 
<!-- create details section to collapse multiple no-output code blocks to save space -->
<details style="color: lightgray;"> 
  <summary>Expand Code</summary> 
  
```{r setup, include = TRUE}
# Load Libraries
start_time_all <- Sys.time()

options(warn = 1)  # output warnings as they appear for traceability in stdout/stderr record

knitr::opts_chunk$set(echo = TRUE, warning = FALSE) # warnings will go to console

quiet_library <- function(...) {
  suppressPackageStartupMessages(library(...))
}
quiet_library(qcreporter)        # dependency of H5MANIPULATOR
quiet_library(Matrix)        # dependency of H5MANIPULATOR
quiet_library(rhdf5)         # dependency of H5MANIPULATOR
quiet_library(H5MANIPULATOR)    
quiet_library(ggplot2)
quiet_library(stringr)       
quiet_library(dplyr)         # data wrangling
quiet_library(cowplot)       # arranging multiple plots
quiet_library(gt)            # formatted table output
quiet_library(plotly)        # interactive plots
quiet_library(tidyr)         # data wrangling
quiet_library(Seurat)        # Sample umap creation
quiet_library(future)        # multi-threading for Sample umap creation
quiet_library(future.apply)  # multi-threading for Sample umap creation
quiet_library(rio)
quiet_library(purrr)
quiet_library(scCustomize)
quiet_library(egg)
quiet_library(DT)
quiet_library(SoupX)
quiet_library(reticulate)
quiet_library(glmpca)
quiet_library(SeuratWrappers)
quiet_library(FlexDotPlot)
quiet_library(viridis)
quiet_library(qs)
quiet_library(gridExtra)
quiet_library(plyr)
quiet_library(circlize)
quiet_library(ComplexHeatmap)
quiet_library(EnhancedVolcano)
quiet_library(naniar)
quiet_library(ggpubr)
quiet_library(XML)
quiet_library(RCurl)
quiet_library(DoubletFinder)
stm("Starting scATAC Seq QC Report")

stm(paste(c("\t",paste(names(Sys.info()),Sys.info(),sep = ": ")), collapse = "\n\t"))  
```  

Argument Parsing  
```{r parse_arguments}
# give input directory rna-specific name 
in_sample <-  params$in_sample  
in_method_string <- params$in_method
in_dir <- params$in_dir  
in_key <- params$in_key  
out_dir <- params$out_dir
```

Check input files  
```{r check_input_main}
if(!dir.exists(in_dir)) {
  stm(paste("ERROR: Cannot find IN results dir:", in_dir))
  stop()
}
if(!file.exists(in_key)) {
  stm(paste("ERROR: Cannot find IN sample key:", in_key))
  stop()
}
if(!dir.exists(out_dir)) {
  stm(paste("Creating output directory:", out_dir))
  dir.create(out_dir)
}

out_prefix <- file.path(out_dir, paste0(in_sample, "_"))

```

Read in the sample key  
```{r read_key}
stm("Reading in sample key")
df_key <- data.table::fread(in_key)
```

Determine which modalities streams were run  
```{r determine_modalities}
defined_modalities <- c("scrna", "scatac", "adt", "hto")

# convert method string to vector
in_method <- strsplit(in_method_string, split = ";")[[1]]
in_method <- tolower(in_method)

# Logic check input methods
if(!all(in_method %in% defined_modalities)){
    unknowns <- setdiff(in_method, defined_modalities)
    stop(sprintf("One or more input methods are not in defined modalities: '%s'. Defined modalities are: [%s]. Input methods should be passed as a ';'-delimited string, ie 'scrna;scatac;hto'.",
                    paste(unknowns, collapse = "', '"),
                    paste(defined_modalities, collapse = ', ')))
} 

has_rna <- "scrna" %in% in_method
has_atac <- "scatac" %in% in_method
has_adt <- "adt" %in% in_method
has_hto <- "hto" %in% in_method

```  
Define and check input folder expectations  
```{r define_input_folders}
if(has_rna){
  in_rna <- file.path(in_dir, "scrna")
  if(!dir.exists(in_rna)){
    stop(sprintf("Expected RNA input directory [%s] does not exist.", in_rna))
  }
}

if(has_atac){
  in_atac <- file.path(in_dir, "atac_qc")
  if(!dir.exists(in_atac)){
    stop(sprintf("Expected ATAC input directory [%s] does not exist.", in_atac))
  }
}

if(has_adt){
  in_adt <- file.path(in_dir, "adt")
  if(!dir.exists(in_adt)){
    stop(sprintf("Expected ADT input directory [%s] does not exist.", in_adt))
  }
}

if(has_hto){
  in_hto <- file.path(in_dir, "hto")
  if(!dir.exists(in_hto)){
    stop(sprintf("Expected HTO input directory [%s] does not exist.", in_hto))
  }
}
```

</details> 

### Sample Information    

```{r batchinfo, include = TRUE}
stm("Constructing Batch Information table")
# Summarize batch information, also declare some global batch variables that are used throughout the report
samples <- unique(df_key$SampleID)
n_samples <- length(samples)
labels <- c("N Samples")
values <-  c(n_samples)
simple_html_table(labels, values, fontsize = 3, col_widths_px = c(175, 850))

sum_file <- list.files(in_atac, 
                         pattern = "summary.csv",
                         full.names = TRUE)
sum <- read.csv(sum_file)
col_to_keep <- names(sum) %in% c("ATAC.Sequenced.read.pairs","ATAC.Valid.barcodes","ATAC.Q30.bases.in.barcode","ATAC.Q30.bases.in.read.1",
                                 "ATAC.Q30.bases.in.read.2","ATAC.Q30.bases.in.sample.index.i1","ATAC.Percent.duplicates")

df <- sum[col_to_keep]

Labels <- c("Sequenced Read Pairs","Valid Barcodes","Q30 Bases in Barcode","Q30 Bases in Read 1",
            "Q30 Bases in Read 2","Q30 Bases in Sample Index i1","Percent Duplicates")
Values <- c(df$ATAC.Sequenced.read.pairs,df$ATAC.Valid.barcodes,df$ATAC.Q30.bases.in.barcode,df$ATAC.Q30.bases.in.read.1,
            df$ATAC.Q30.bases.in.read.2,df$ATAC.Q30.bases.in.sample.index.i1,df$ATAC.Percent.duplicates)

simple_html_table(Labels, Values, fontsize = 3, col_widths_px = c(175, 850))
```  
```{r atac_tab, results = "asis", eval = has_atac, echo = FALSE}
cat("## scATAC", sep = "\n")
```  
```{r atac_child, child =  system.file("rmarkdown/scatac_seq_module.Rmd", package = "scATACSeqPipeline"), eval =  has_atac}
```   

## Session Information   

<a id="top_session_info"></a>  

Input Directory:  

```{r echo_in_dir}
in_dir 

```  
Input Directory Contents:  

```{r echo_in_files}
folders <- list.dirs(in_dir, recursive = FALSE)

file_list <- lapply(folders, function(x){
  dir(x, recursive = TRUE)
})
names(file_list) <- basename(folders)
file_list

```  


Key File:  
```{r echo_key_files}
in_key

```  

Output Directory:  
```{r echo_out_dir}
out_dir

``` 
