#' Perform Jaccard-Louvain clustering of ATAC LSI results
#'
#' @param lsi_mat A matrix of LSI results, as generated by atac_lsi()
#' @param k A numeric object specifying the number of K-nearest neighbors to use for clustering
#' @param mutual A logical object specifying whether or not to exlusively use mutual nearest neighbors for clustering
#' @param radius A maximum radius to use to restrict neighbor distance. Default is NULL, which will not impose this restriction.
#'
#' @return a list object with a cluster factor object (cl), modularity scores for each cluster, and the results generated by igraph::cluster_louvain()
#' @export
atac_clustering <- function(lsi_mat,
                            k = 30,
                            mutual = FALSE,
                            radius = NULL) {
  # from scrattch.hicat
  if(!is.null(radius)) {
    knn <- RANN::nn2(lsi_mat, k = k, searchtype = "radius", radius = radius)[[1]]
  } else {
    knn <- RANN::nn2(lsi_mat, k = k)[[1]]
  }

  if(mutual) {
    knn <- t(apply(knn,
                   1,
                   function(x) {
                     a <- x[1]
                     b <- x[-1]
                     mnn <- sapply(b,
                                   function(y) {
                                     a %in% knn[y,]
                                   })
                     b[!mnn] <- 0
                     c(a,b)
                   }))
  }

  knn.df <- data.frame(i = rep(1:nrow(knn),
                               ncol(knn)),
                       j = as.vector(knn))
  knn.df <- knn.df[knn.df$j > 0,]

  knn.mat <- Matrix::sparseMatrix(i = knn.df[[1]],
                                  j = knn.df[[2]],
                                  x = 1)

  jaccard.adj  <- sparse_jaccard(knn.mat)
  jaccard.gr <- igraph::graph.adjacency(jaccard.adj,
                                        mode = "undirected",
                                        weighted = TRUE)
  louvain.result <- igraph::cluster_louvain(jaccard.gr)
  mod.sc <- igraph::modularity(louvain.result)

  cl <- setNames(louvain.result$membership,
                 rownames(lsi_mat))

  list(cl = cl,
       modularity = mod.sc,
       louvain_result = louvain.result)
}
